export const bankCodeList = [
  {
    value: "000",
    label: "은행",
    code: 0,
    codeKo: "은행",
    codeEn: "BANK",
  },
  {
    value: "039",
    label: "경남은행",
    code: 39,
    codeKo: "경남",
    codeEn: "KYONGNAMBANK",
  },
  {
    value: "034",
    label: "광주은행",
    code: 34,
    codeKo: "광주",
    codeEn: "GWANGJUBANK",
  },
  {
    value: "012",
    label: "단위농협(지역농축협)",
    code: 12,
    codeKo: "단위농협",
    codeEn: "LOCALNONGHYEOP",
  },
  {
    value: "032",
    label: "부산은행",
    code: 32,
    codeKo: "부산",
    codeEn: "BUSANBANK",
  },
  {
    value: "045",
    label: "새마을금고",
    code: 45,
    codeKo: "새마을",
    codeEn: "SAEMAUL",
  },
  {
    value: "064",
    label: "산림조합",
    code: 64,
    codeKo: "산림",
    codeEn: "SANLIM",
  },
  {
    value: "088",
    label: "신한은행",
    code: 88,
    codeKo: "신한",
    codeEn: "SHINHAN",
  },
  {
    value: "048",
    label: "신협",
    code: 48,
    codeKo: "신협",
    codeEn: "SHINHYEOP",
  },
  { value: "027", label: "씨티은행", code: 27, codeKo: "씨티", codeEn: "CITI" },
  {
    value: "020",
    label: "우리은행",
    code: 20,
    codeKo: "우리",
    codeEn: "WOORI",
  },
  {
    value: "071",
    label: "우체국예금보험",
    code: 71,
    codeKo: "우체국",
    codeEn: "POST",
  },
  {
    value: "050",
    label: "저축은행중앙회",
    code: 50,
    codeKo: "저축",
    codeEn: "SAVINGBANK",
  },
  {
    value: "037",
    label: "전북은행",
    code: 37,
    codeKo: "전북",
    codeEn: "JEONBUKBANK",
  },
  {
    value: "035",
    label: "제주은행",
    code: 35,
    codeKo: "제주",
    codeEn: "JEJUBANK",
  },
  {
    value: "090",
    label: "카카오뱅크",
    code: 90,
    codeKo: "카카오",
    codeEn: "KAKAOBANK",
  },
  {
    value: "089",
    label: "케이뱅크",
    code: 89,
    codeKo: "케이",
    codeEn: "KBANK",
  },
  {
    value: "092",
    label: "토스뱅크",
    code: 92,
    codeKo: "토스",
    codeEn: "TOSSBANK",
  },
  { value: "081", label: "하나은행", code: 81, codeKo: "하나", codeEn: "HANA" },
  {
    value: "054",
    label: "홍콩상하이은행",
    code: 54,
    codeKo: "",
    codeEn: "HSBC",
  },
  {
    value: "003",
    label: "IBK기업은행",
    code: 3,
    codeKo: "기업",
    codeEn: "IBK",
  },
  {
    value: "004",
    label: "KB국민은행",
    code: 6,
    codeKo: "국민",
    codeEn: "KOOKMIN",
  },
  {
    value: "031",
    label: "iM뱅크(대구)",
    code: 31,
    codeKo: "대구",
    codeEn: "DAEGUBANK",
  },
  {
    value: "002",
    label: "한국산업은행",
    code: 2,
    codeKo: "산업",
    codeEn: "KDBBANK",
  },
  {
    value: "011",
    label: "NH농협은행",
    code: 11,
    codeKo: "농협",
    codeEn: "NONGHYEOP",
  },
  {
    value: "023",
    label: "SC제일은행",
    code: 23,
    codeKo: "SC제일",
    codeEn: "SC",
  },
  {
    value: "007",
    label: "Sh수협은행",
    code: 7,
    codeKo: "수협",
    codeEn: "SUHYEOP",
  },
];
